image:
  - Visual Studio 2017

platform:
  - Win32
  - x64

environment:
  LMFIT_TAG: v8.2.2
  ZIP_NAME: lmfit_%LMFIT_TAG%_windows_%PLATFORM%_%toolset%
  matrix:
  # - toolset: v90
  - toolset: v140

install:
  # - git clone -b %LMFIT_TAG% https://jugit.fz-juelich.de/mlz/lmfit
  - git clone https://jugit.fz-juelich.de/mlz/lmfit
  # - copy /Y CMakeLists.txt lmfit

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%\lmfit
  - cmake . -Bbin -A%PLATFORM% -T%toolset% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\lmfit\bin
  - cmake --build . --config RELEASE --target INSTALL

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\install
  - 7z a %ZIP_NAME%.zip * -r # zip
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir deployment
  - copy install\%ZIP_NAME%.zip deployment\%ZIP_NAME%.zip

artifacts:
  - path: deployment\*.*

deploy:
  provider: GitHub
  release: lmfit_$(lmfit_TAG)
  auth_token:
    secure: J21nvYa1j0K5KlxFo+HRmHh7usNai+gOoSjwYFCbYuVfip3buosHdN99ltY677MY
  draft: false
  prerelease: false
  force_update: true
